from nengo.spa import SPA
from nengo.spa.actions import Actions
from nengo.spa.assoc_mem import AssociativeMemory
from nengo.spa.basalganglia import BasalGanglia
from .buffer import Buffer
from .compare import Compare
from .circularconvolution import CircularConvolution
from nengo.spa.cortical import Cortical
from nengo.spa.input import Input
from .memory import Memory
from nengo.spa.module import Module
from .product import Product
from nengo.spa.utils import similarity
from nengo.spa.thalamus import Thalamus
from .unitea import UnitEA
from nengo.spa.vocab import Vocabulary
